/// <reference lib="webworker" />
import {
	precacheAndRoute,
	cleanupOutdatedCaches,
	createHandlerBoundToURL
} from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { clientsClaim } from 'workbox-core';

/**
 * Service worker (precache manifest injected at build time by @vite-pwa/sveltekit).
 *
 * Responsibilities:
 * - Precache the application shell so the app opens offline after the first load.
 * - Runtime-cache navigations and face models (`/models/*`) — the models are large,
 *   so they are not precached on install.
 * - Handle `SKIP_WAITING` messages sent by the in-app update prompt.
 *
 * The service worker is NOT a database: all application data lives in IndexedDB.
 */

declare let self: ServiceWorkerGlobalScope & {
	__WB_MANIFEST: Array<{ url: string; revision: string | null }>;
};

cleanupOutdatedCaches();

// Shell assets (JS/CSS/HTML/icons) generated by the build.
precacheAndRoute(self.__WB_MANIFEST);

// Navigation requests: try the network first, fall back to the cached page,
// and finally to the prerendered /offline page.
const navigationHandler = new NetworkFirst({
	cacheName: 'pages',
	networkTimeoutSeconds: 5,
	plugins: [
		new ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 60 * 60 * 24 * 30 }),
		new CacheableResponsePlugin({ statuses: [0, 200] })
	]
});
registerRoute(new NavigationRoute(navigationHandler, { denylist: [/^\/api\//] }));

// Face recognition models — large binaries, cached on first use.
registerRoute(
	({ url }) => url.pathname.startsWith('/models/'),
	new CacheFirst({
		cacheName: 'face-models',
		plugins: [new ExpirationPlugin({ maxEntries: 40, maxAgeSeconds: 60 * 60 * 24 * 365 })]
	})
);

// Web fonts.
registerRoute(
	({ request }) => request.destination === 'font',
	new CacheFirst({
		cacheName: 'fonts',
		plugins: [new ExpirationPlugin({ maxEntries: 20, maxAgeSeconds: 60 * 60 * 24 * 365 })]
	})
);

// Apply a waiting update immediately when the app asks for it.
self.addEventListener('message', (event) => {
	if (event.data && event.data.type === 'SKIP_WAITING') {
		self.skipWaiting();
	}
});

// Take control of open pages as soon as the worker activates.
clientsClaim();
self.addEventListener('activate', (event) => {
	event.waitUntil(self.clients.claim());
});

export {};
